"use client";
import { useEffect,useMemo,useRef,useState,type PointerEvent as ReactPointerEvent } from "react";

type Kind="idea"|"project";
type Section=Kind|"plan"|"calendar"|"report"|"tools"|"software";
type Entry={id:string;kind:Kind;title:string;tags:string[];createdAt:string;lastViewed:string;cover?:string;source?:string;pinned?:boolean;originId?:string};
type Bubble={id:string;x:number;y:number;vx:number;vy:number;size:number;variant:number};
type Preferences={compact:boolean;showSystem:boolean;density:number;motionSpeed:number;aging:boolean;defaultMode:"drift"|"index";sound:boolean;boot:boolean};
const defaults:Preferences={compact:false,showSystem:true,density:12,motionSpeed:1,aging:true,defaultMode:"drift",sound:true,boot:true};
const DAY=86400000;
const seed:Entry[]=[
 {id:"MEM-024",kind:"idea",title:"个人工作台",tags:["PRODUCT","UI"],createdAt:"2026-08-09",lastViewed:"2026-08-09",pinned:true},
 {id:"MEM-018",kind:"idea",title:"会呼吸的桌面",tags:["INTERACTION"],createdAt:"2026-07-28",lastViewed:"2026-08-03"},
 {id:"MEM-015",kind:"idea",title:"城市声音地图",tags:["MAP","AUDIO"],createdAt:"2026-07-19",lastViewed:"2026-07-22"},
 {id:"MEM-012",kind:"idea",title:"机械结构生成器",tags:["TOOL","CAD"],createdAt:"2026-06-30",lastViewed:"2026-07-08"},
 {id:"MEM-009",kind:"idea",title:"空间音频可视化",tags:["AUDIO","VISUAL"],createdAt:"2026-06-12",lastViewed:"2026-06-20"},
 {id:"MEM-006",kind:"idea",title:"模块化家具",tags:["DESIGN"],createdAt:"2026-05-04",lastViewed:"2026-05-12"},
 {id:"MEM-003",kind:"idea",title:"电影中的控制台",tags:["REFERENCE","UI"],createdAt:"2026-03-17",lastViewed:"2026-04-01"},
 {id:"MEM-001",kind:"idea",title:"未完成的远行计划",tags:["LIFE"],createdAt:"2026-01-08",lastViewed:"2026-01-18"}
];
const age=(d:string)=>Math.max(0,Math.floor((Date.now()-new Date(d).getTime())/DAY));
function makeBubbles(es:Entry[]):Bubble[]{return es.map((e,i)=>{const s=e.pinned?122:Math.max(62,120-age(e.lastViewed)*.38);return{id:e.id,x:95+(i*181)%920,y:85+(i*131)%510,vx:(i%2?1:-1)*(.13+(i%4)*.025),vy:(i%3?1:-1)*(.09+(i%3)*.025),size:s,variant:i%3}})}
function tone(kind:"boot"|"select"|"open"){try{const C=window.AudioContext||((window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext);const c=new C(),g=c.createGain();g.connect(c.destination);const now=c.currentTime;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.12,now+.018);g.gain.exponentialRampToValueAtTime(.0001,now+(kind==="boot"?.9:.16));[kind==="boot"?88:420,kind==="boot"?176:630].forEach((f,i)=>{const o=c.createOscillator();o.type=i?"square":"sine";o.frequency.setValueAtTime(f,now);if(kind==="boot")o.frequency.exponentialRampToValueAtTime(f*1.8,now+.75);o.connect(g);o.start(now+i*.04);o.stop(now+(kind==="boot"?.92:.17))});setTimeout(()=>c.close(),1200)}catch{}}

export default function Workbench(){
 const[entries,setEntries]=useState<Entry[]>(seed),[section,setSection]=useState<Section>("idea"),[mode,setMode]=useState<"drift"|"hold"|"index">("drift"),[drawer,setDrawer]=useState(false),[query,setQuery]=useState(""),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<string|null>(null),[adding,setAdding]=useState(false),[settings,setSettings]=useState(false),[prefs,setPrefs]=useState<Preferences>(defaults),[boot,setBoot]=useState<"waiting"|"loading"|"done">("waiting"),[bubbles,setBubbles]=useState<Bubble[]>(()=>makeBubbles(seed)),[mouse,setMouse]=useState({x:-999,y:-999});
 const zone=useRef<HTMLDivElement>(null),bref=useRef(bubbles),href=useRef<string|null>(null),eref=useRef(entries);
 useEffect(()=>{try{const e=localStorage.getItem("memory-workbench-entries"),p=localStorage.getItem("memory-workbench-preferences");if(e)setEntries(JSON.parse(e));if(p){const x={...defaults,...JSON.parse(p)};setPrefs(x);setMode(x.defaultMode);if(!x.boot)setBoot("done")}}catch{}},[]);
 useEffect(()=>{eref.current=entries;localStorage.setItem("memory-workbench-entries",JSON.stringify(entries))},[entries]);
 useEffect(()=>localStorage.setItem("memory-workbench-preferences",JSON.stringify(prefs)),[prefs]);
 useEffect(()=>{bref.current=bubbles},[bubbles]);
 useEffect(()=>setBubbles(makeBubbles(entries.filter(e=>e.kind==="idea").slice(0,prefs.density))),[entries,prefs.density]);
 useEffect(()=>{let f=0;const tick=()=>{const z=zone.current;if(z&&mode==="drift"){const w=z.clientWidth,h=z.clientHeight,n=bref.current.map(b=>({...b}));for(const b of n){const d=Math.hypot(mouse.x-b.x,mouse.y-b.y),slow=d<150?Math.max(.08,d/150):1,k=href.current===b.id?0:slow;b.vx*=.999;b.vy*=.999;b.x+=b.vx*k*prefs.motionSpeed;b.y+=b.vy*k*prefs.motionSpeed;if(prefs.aging&&age(eref.current.find(e=>e.id===b.id)?.lastViewed||"2026-08-10")>75)b.y+=.025;const r=b.size/2;if(b.x<r+12){b.x=r+12;b.vx=Math.abs(b.vx)}if(b.x>w-r-12){b.x=w-r-12;b.vx=-Math.abs(b.vx)}if(b.y<r+12){b.y=r+12;b.vy=Math.abs(b.vy)}if(b.y>h-r-12){b.y=h-r-12;b.vy=-Math.abs(b.vy)*.65}}for(let i=0;i<n.length;i++)for(let j=i+1;j<n.length;j++){const a=n[i],b=n[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,m=(a.size+b.size)/2+8;if(d<m){const nx=dx/d,ny=dy/d,p=(m-d)/2;a.x-=nx*p;a.y-=ny*p;b.x+=nx*p;b.y+=ny*p;const av=a.vx*nx+a.vy*ny,bv=b.vx*nx+b.vy*ny;a.vx+=(bv-av)*nx*.5;a.vy+=(bv-av)*ny*.5;b.vx+=(av-bv)*nx*.5;b.vy+=(av-bv)*ny*.5}}bref.current=n;setBubbles(n)}f=requestAnimationFrame(tick)};f=requestAnimationFrame(tick);return()=>cancelAnimationFrame(f)},[mode,mouse,prefs.motionSpeed,prefs.aging]);
 const ideas=entries.filter(e=>e.kind==="idea"),projects=entries.filter(e=>e.kind==="project"),current=entries.find(e=>e.id===selected),item=entries.find(e=>e.id===detail),filtered=useMemo(()=>ideas.filter(e=>[e.title,...e.tags,e.createdAt].join(" ").toLowerCase().includes(query.toLowerCase())),[ideas,query]);
 const open=(id:string)=>{if(prefs.sound)tone("open");setEntries(v=>v.map(e=>e.id===id?{...e,lastViewed:new Date().toISOString().slice(0,10)}:e));setDetail(id);setSelected(null)};
 const convert=(id:string)=>{setEntries(v=>v.map(e=>e.id===id?{...e,id:`PRJ-${String(v.filter(x=>x.kind==="project").length+1).padStart(3,"0")}`,kind:"project",originId:id}:e));setSelected(null);setDetail(null);setSection("project")};
 const add=(title:string,source:string)=>{if(!title.trim())return;const n=entries.filter(e=>e.kind==="idea").length+25,t=new Date().toISOString().slice(0,10);setEntries(v=>[{id:`MEM-${String(n).padStart(3,"0")}`,kind:"idea",title:title.trim(),tags:["NEW"],createdAt:t,lastViewed:t,source:source||undefined},...v]);setAdding(false)};
 if(boot!=="done")return <Boot complete={()=>setBoot("done")}/>;
 if(item)return <main className="detail-page"><header className="detail-head"><button onClick={()=>setDetail(null)}>← RETURN / 返回</button><span>{item.id}</span></header><div className="detail-grid"><aside><b>{item.kind==="idea"?"MEMORY DATA":"PROJECT DATA"}</b><small>ENTRY / {item.id}</small></aside><section><p className="eyebrow">{item.kind==="idea"?"灵感档案":"项目档案"}</p><h1>{item.title}</h1><div className="yellow-line"/><p className="empty-copy">CONTENT MODULE NOT DEPLOYED<br/>内容模块暂未部署</p>{item.kind==="idea"&&<button className="primary" onClick={()=>convert(item.id)}>CONVERT TO PROJECT / 转化为项目</button>}</section></div></main>;
 const selectSection=(k:Section)=>{if(prefs.sound)tone("select");setSection(k)};
 const meta:Record<Section,[string,string]>={project:["项目管理","已部署的工程档案 · 连接目录与进展"],idea:["创作灵感","漂浮的记忆单元 · 捕获、检索并转化为项目"],plan:["今日计划","按时间组织今天的行动与重点"],calendar:["日历","按月查看计划、项目节点与灵感记录"],report:["日报 / 周报","聚合项目进展、计划完成与灵感活动"],tools:["工具","管理生成器、脚本与常用能力"],software:["软件入口","快速启动本机软件与工作环境"]};
 return <main className={`field-shell ${prefs.compact?"compact":""}`} data-theme="day">
  <aside className="field-sidebar nav-only-sidebar"><ModuleSwitcher section={section} select={selectSection} settings={()=>setSettings(true)}/></aside>
  <section className="field-main"><header className="field-top"><div><span>WB / 00.03</span><b>// OPERATIONS</b><i/></div>{prefs.showSystem&&<p>LOCAL CORE　 <strong>SYSTEM ONLINE</strong></p>}</header>
   <div className="field-content"><div className="field-title"><small>FIELD OPERATIONS / CONTROL TERMINAL</small><h1>{meta[section][0]}</h1><p>{meta[section][1]}</p><div className="microline"/></div>
    {section==="project"?<ProjectView projects={projects} open={setDetail} goto={()=>setSection("idea")}/>:section==="plan"?<PlanView/>:section==="calendar"?<CalendarView/>:section==="report"?<ReportView/>:section==="tools"?<EmptyModule code="TOOLS / 06" title="工具模块待部署" text="后续将在这里管理生成器、脚本和快捷工具。"/>:section==="software"?<EmptyModule code="SOFTWARE / 07" title="软件入口待部署" text="后续将在这里添加本机软件快捷方式。"/>:<section className="memory-module"><header><div><b>忆泡场</b><small>// MEMORY FIELD</small></div><div className="memory-actions"><button className={mode==="hold"?"active":""} title={mode==="hold"?"继续漂浮":"暂停漂浮"} aria-label={mode==="hold"?"继续漂浮":"暂停漂浮"} onClick={()=>setMode(mode==="hold"?"drift":"hold")}>{mode==="hold"?"▶":"Ⅱ"}</button><button className={mode==="index"?"active":""} title="静态排列" aria-label="静态排列" onClick={()=>setMode(mode==="index"?"drift":"index")}>▦</button><button title="刷新忆泡" aria-label="刷新忆泡" onClick={()=>setBubbles(makeBubbles(ideas.slice(0,prefs.density)))}>↻</button><button title="新建灵感" aria-label="新建灵感" onClick={()=>setAdding(true)}>＋</button><button className={drawer?"active":""} title="检索灵感" aria-label="检索灵感" onClick={()=>setDrawer(v=>!v)}>⌕</button></div><span>{ideas.length} / DATA</span></header><div ref={zone} className="memory-zone field-zone" onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();setMouse({x:e.clientX-r.left,y:e.clientY-r.top})}} onMouseLeave={()=>setMouse({x:-999,y:-999})}>{bubbles.map((b,i)=>{const e=ideas.find(x=>x.id===b.id);if(!e)return null;const grid=mode==="index",cols=Math.max(3,Math.floor((zone.current?.clientWidth||900)/165)),x=grid?95+(i%cols)*160:b.x,y=grid?100+Math.floor(i/cols)*155:b.y;return <button key={b.id} className={`bubble v${b.variant} ${selected===b.id?"selected":""} ${selected&&selected!==b.id?"dim":""}`} style={{width:b.size,height:b.size,transform:`translate3d(${x-b.size/2}px,${y-b.size/2}px,0)`}} onMouseEnter={()=>href.current=b.id} onMouseLeave={()=>href.current=null} onClick={()=>{if(prefs.sound)tone("select");setSelected(b.id)}}><span className="bubble-id">{b.id.slice(4)}</span><b>{e.title}</b><i/></button>})}{current&&<div className="inspector"><small>IDENTIFIED / {current.id}</small><h3>{current.title}</h3><dl><div><dt>CREATED</dt><dd>{current.createdAt}</dd></div><div><dt>LAST VIEW</dt><dd>{age(current.lastViewed)} DAYS AGO</dd></div><div><dt>TAG</dt><dd>{current.tags.join(" / ")}</dd></div></dl><div className="inspector-actions"><button onClick={()=>open(current.id)}>OPEN / 打开</button><button onClick={()=>convert(current.id)}>CONVERT / 转项目</button></div><button className="close" onClick={()=>setSelected(null)}>×</button></div>}<SearchDrawer open={drawer} close={()=>setDrawer(false)} query={query} setQuery={setQuery} items={filtered} pick={id=>{setSelected(id);setDrawer(false)}}/></div></section>}
   </div>
  </section>
  {adding&&<AddDialog close={()=>setAdding(false)} add={add}/>} {settings&&<Settings prefs={prefs} setPrefs={setPrefs} close={()=>setSettings(false)}/>}<ProjectAIOrb project={projects[0]}/><footer><span>UNOFFICIAL PERSONAL WORKBENCH</span><span>BUILD 0.5.0 / READY</span></footer>
 </main>
}

function ModuleSwitcher({section,select,settings}:{section:Section;select:(s:Section)=>void;settings:()=>void}){const items:[Section,string,string][]=[["project","项目管理","PROJECT"],["idea","创作灵感","MEMORY"],["plan","今日计划","PLAN"],["calendar","日历","CALENDAR"],["report","日报 / 周报","REPORT"],["tools","工具","TOOLS"],["software","软件入口","SOFTWARE"]];return <nav className="module-switcher" aria-label="模块切换">{items.map(([key,label,code],i)=><button key={key} className={section===key?"active":""} onClick={()=>select(key)} title={label}><em>{String(i+1).padStart(2,"0")}</em><b>{label}</b><small>{code}</small></button>)}<button onClick={settings} title="基础设置"><em>08</em><b>基础设置</b><small>SYSTEM</small></button></nav>}

function Boot({complete}:{complete:()=>void}){const[progress,setProgress]=useState(0);useEffect(()=>{let finished=0,cancelled=false;const resources=["/admin-silhouette.png","/brand-logo.png"],advance=()=>{finished+=1;if(!cancelled)setProgress(Math.min(100,finished/resources.length*100))};resources.forEach(src=>{const image=new Image();image.onload=advance;image.onerror=advance;image.src=src});return()=>{cancelled=true}},[]);const value=progress.toFixed(2),ready=progress>=100;return <main className={`boot boot-empty ${ready?"ready":""}`} onClick={ready?complete:undefined}><div className="boot-walker" aria-label="管理员剪影"><img src="/admin-silhouette.png" alt=""/></div><img className="boot-title-logo" src="/brand-logo.png" alt="终端工作台"/><button className="boot-continue" disabled={!ready} onClick={complete}>点击任意位置继续<span>▶</span></button><div className="boot-progress" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress} aria-label={`系统加载进度 ${value}%`}><p>//正在检查资源完整性...（{value}%）</p><div className="boot-progress-track"><i style={{width:`${progress}%`}}/></div></div></main>}
function ProjectView({projects,open,goto}:{projects:Entry[];open:(id:string)=>void;goto:()=>void}){return <section className="project-module">{projects.length?projects.map(p=><button key={p.id} onClick={()=>open(p.id)}><small>{p.id} / ACTIVE</small><h3>{p.title}</h3><span>SOURCE　{p.originId||"MANUAL"}</span><i>OPEN →</i></button>):<div className="empty"><span>NO DEPLOYED PROJECT</span><h2>暂无已部署项目</h2><p>将灵感转化为项目后，它会在这里形成结构化档案。</p><button onClick={goto}>OPEN MEMORY / 前往灵感</button></div>}</section>}
function PlanView(){const[done,setDone]=useState<number[]>([]);const plans=[["09:00","整理今日重点","工作"],["11:00","查看项目进展","项目"],["15:30","记录一个新灵感","灵感"]];return <section className="operation-module plan-module"><header><div><b>今日行动序列</b><small>// DAILY OPERATION</small></div><time>{new Date().toLocaleDateString("zh-CN")}</time><button>＋ 新增计划</button></header><div className="plan-list">{plans.map((p,i)=><button key={p[0]} className={done.includes(i)?"done":""} onClick={()=>setDone(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i])}><time>{p[0]}</time><span><b>{p[1]}</b><small>{p[2]} / TASK-{String(i+1).padStart(2,"0")}</small></span><i>{done.includes(i)?"✓":"○"}</i></button>)}</div><footer><b>{done.length} / {plans.length}</b><span>今日计划完成度</span><div><i style={{width:`${done.length/plans.length*100}%`}}/></div></footer></section>}
function CalendarView(){const today=new Date(),[cursor,setCursor]=useState(()=>new Date(today.getFullYear(),today.getMonth(),1)),[selected,setSelected]=useState(()=>today.toISOString().slice(0,10));const y=cursor.getFullYear(),m=cursor.getMonth(),offset=(new Date(y,m,1).getDay()+6)%7,count=new Date(y,m+1,0).getDate(),prevCount=new Date(y,m,0).getDate(),cells=Array.from({length:42},(_,i)=>{const n=i-offset+1;if(n<1)return{date:new Date(y,m-1,prevCount+n),muted:true};if(n>count)return{date:new Date(y,m+1,n-count),muted:true};return{date:new Date(y,m,n),muted:false}}),key=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`,events:Record<string,string[]>={[key(today)]:["09:00 整理今日重点","11:00 查看项目进展","15:30 记录一个新灵感"],[key(new Date(y,m,15))]:["项目阶段检查"],[key(new Date(y,m,22))]:["周报整理"]},chosen=events[selected]||[];const move=(n:number)=>setCursor(new Date(y,m+n,1)),reset=()=>{setCursor(new Date(today.getFullYear(),today.getMonth(),1));setSelected(key(today))};return <section className="operation-module calendar-module"><header><div><b>月度行动日历</b><small>// OPERATION CALENDAR</small></div><div className="calendar-nav"><button onClick={()=>move(-1)}>←</button><strong>{y} / {String(m+1).padStart(2,"0")}</strong><button onClick={()=>move(1)}>→</button></div><button onClick={reset}>TODAY / 今天</button></header><div className="calendar-layout"><div className="calendar-board"><div className="calendar-week">{["MON","TUE","WED","THU","FRI","SAT","SUN"].map(x=><b key={x}>{x}</b>)}</div><div className="calendar-grid">{cells.map(({date,muted})=>{const k=key(date),isToday=k===key(today),active=k===selected,items=events[k]||[];return <button key={k} className={`${muted?"muted":""} ${isToday?"today":""} ${active?"selected":""}`} onClick={()=>setSelected(k)}><time>{String(date.getDate()).padStart(2,"0")}</time>{items.slice(0,2).map((e,i)=><span key={i}>{e.replace(/^\d\d:\d\d\s/,"")}</span>)}{items.length>2&&<small>+{items.length-2}</small>}</button>})}</div></div><aside className="calendar-agenda"><small>SELECTED DATE</small><h2>{selected.replaceAll("-",".")}</h2><div className="calendar-rule"/><b>{chosen.length} / EVENTS</b>{chosen.length?chosen.map((e,i)=><article key={i}><i>{String(i+1).padStart(2,"0")}</i><span>{e}</span></article>):<p>该日期暂无安排。<br/>可从今日计划中添加日程。</p>}<button>＋ ADD SCHEDULE / 新增日程</button></aside></div></section>}
function ReportView(){const[type,setType]=useState<"daily"|"weekly">("daily");return <section className="operation-module report-module"><header><div><b>进展汇总</b><small>// ACTIVITY REPORT</small></div><div><button className={type==="daily"?"active":""} onClick={()=>setType("daily")}>日报</button><button className={type==="weekly"?"active":""} onClick={()=>setType("weekly")}>周报</button></div><button>GENERATE / 生成</button></header><div className="report-grid"><article><small>{type==="daily"?"DAILY REPORT":"WEEKLY REPORT"} / DRAFT</small><h2>{type==="daily"?"今日工作摘要":"本周工作摘要"}</h2><p>当前暂无已生成内容。未来将自动汇总项目进展、已完成计划、查看过的灵感和Git提交记录。</p><span>WAITING FOR ACTIVITY DATA</span></article><aside><b>DATA SOURCE</b><dl><div><dt>完成计划</dt><dd>0</dd></div><div><dt>项目动态</dt><dd>0</dd></div><div><dt>灵感活动</dt><dd>0</dd></div></dl></aside></div></section>}
function EmptyModule({code,title,text}:{code:string;title:string;text:string}){return <section className="operation-module empty-module"><small>{code}</small><h2>{title}</h2><p>{text}</p><span>MODULE NOT DEPLOYED</span></section>}
type ChatMessage={id:number;role:"user"|"assistant";text:string;time:string};
function ProjectAIOrb({project}:{project?:Entry}){
 const[open,setOpen]=useState(false),[tab,setTab]=useState<"chat"|"history">("chat"),[text,setText]=useState(""),[messages,setMessages]=useState<ChatMessage[]>([]),[pos,setPos]=useState({x:0,y:420,edge:"right" as "left"|"right"}),[idle,setIdle]=useState(true),[dragging,setDragging]=useState(false);
 const drag=useRef({x:0,y:0,px:0,py:0,moved:false}),idleTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{try{const x=localStorage.getItem("workbench-ai-messages"),p=localStorage.getItem("workbench-ai-position");if(x)setMessages(JSON.parse(x));const saved=p?JSON.parse(p):null,y=saved?.y??Math.max(90,window.innerHeight-150),edge=saved?.edge==="left"?"left":"right";setPos({x:edge==="left"?0:window.innerWidth-70,y:Math.min(y,window.innerHeight-82),edge})}catch{}},[]);
 useEffect(()=>localStorage.setItem("workbench-ai-messages",JSON.stringify(messages)),[messages]);
 useEffect(()=>{if(open){setIdle(false);if(idleTimer.current)clearTimeout(idleTimer.current)}},[open]);
 const rest=()=>{if(idleTimer.current)clearTimeout(idleTimer.current);if(!open)idleTimer.current=setTimeout(()=>setIdle(true),1400)};
 const wake=()=>{setIdle(false);if(idleTimer.current)clearTimeout(idleTimer.current)};
 const down=(e:ReactPointerEvent<HTMLButtonElement>)=>{wake();e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,px:pos.x,py:pos.y,moved:false};setDragging(true)};
 const move=(e:ReactPointerEvent<HTMLButtonElement>)=>{if(!dragging)return;const dx=e.clientX-drag.current.x,dy=e.clientY-drag.current.y;if(Math.hypot(dx,dy)>4)drag.current.moved=true;setPos(v=>({...v,x:Math.max(0,Math.min(window.innerWidth-70,drag.current.px+dx)),y:Math.max(12,Math.min(window.innerHeight-82,drag.current.py+dy))}))};
 const up=(e:ReactPointerEvent<HTMLButtonElement>)=>{if(!dragging)return;e.currentTarget.releasePointerCapture(e.pointerId);setDragging(false);if(!drag.current.moved){setOpen(v=>!v);return}const edge=e.clientX<window.innerWidth/2?"left":"right",y=Math.max(12,Math.min(window.innerHeight-82,drag.current.py+e.clientY-drag.current.y)),next={x:edge==="left"?0:window.innerWidth-70,y,edge};setPos(next);localStorage.setItem("workbench-ai-position",JSON.stringify({edge,y}));rest()};
 const send=()=>{if(!text.trim())return;const now=new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"}),q={id:Date.now(),role:"user" as const,text:text.trim(),time:now};setMessages(v=>[...v,q,{id:Date.now()+1,role:"assistant",text:project?`已收到关于「${project.title}」的问题。AI执行核心尚未连接；接入桌面后端后，我将读取该项目目录并开展操作。`:"当前尚未绑定项目。请先创建项目并连接本地目录。",time:now}]);setText("")};
 return <div className={`ai-orb-wrap edge-${pos.edge} ${open?"open":""} ${idle&&!open?"idle":""} ${dragging?"dragging":""}`} style={{left:pos.x,top:pos.y}} onPointerEnter={wake} onPointerLeave={rest}><button className="ai-orb" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>setDragging(false)} aria-label="项目AI助手"><i/><b>AI</b><span>{messages.length||"+"}</span></button>{open&&<section className="ai-console"><header><div><small>PROJECT INTELLIGENCE / ONLINE</small><h2>项目 AI</h2></div><button onClick={()=>{setOpen(false);rest()}}>×</button></header><div className="ai-project"><span>CONTEXT</span><b>{project?.title||"未绑定项目"}</b><i className={project?"ready":""}>{project?"READY":"OFFLINE"}</i></div><nav><button className={tab==="chat"?"active":""} onClick={()=>setTab("chat")}>对话</button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}>记录</button></nav>{tab==="chat"?<><div className="ai-messages">{messages.length===0?<div className="ai-welcome"><b>PROJECT AGENT</b><p>询问项目结构、下一步计划或让AI协助处理文件。</p><small>桌面执行核心待连接</small></div>:messages.map(m=><article key={m.id} className={m.role}><small>{m.role==="user"?"YOU":"AGENT"} / {m.time}</small><p>{m.text}</p></article>)}</div><div className="ai-input"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="向项目AI发送指令…"/><button onClick={send}>SEND<br/>发送</button></div></>:<div className="ai-history"><header><span>{messages.filter(m=>m.role==="user").length} CONVERSATIONS</span><button onClick={()=>setMessages([])}>CLEAR / 清空</button></header>{messages.filter(m=>m.role==="user").map(m=><button key={m.id} onClick={()=>setTab("chat")}><time>{m.time}</time><span>{m.text}</span><i>→</i></button>)}</div>}<footer><span>MODEL / NOT CONNECTED</span><span>LOCAL RECORD / ENABLED</span></footer></section>}</div>
}
function SearchDrawer({open,close,query,setQuery,items,pick}:{open:boolean;close:()=>void;query:string;setQuery:(s:string)=>void;items:Entry[];pick:(id:string)=>void}){return <aside className={`drawer ${open?"open":""}`}><header><div><small>MEMORY RETRIEVAL</small><h2>灵感检索</h2></div><button onClick={close}>×</button></header><label><span>&gt;</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="输入名称、标签或时间"/></label><p className="result-count">RESULT / {String(items.length).padStart(3,"0")}</p><div className="results">{items.map(e=><button key={e.id} onClick={()=>pick(e.id)}><b>{e.id}</b><span>{e.title}<small>{e.tags.join(" · ")}</small></span><time>{e.createdAt.replaceAll("-",".")}</time></button>)}</div></aside>}
function Settings({prefs,setPrefs,close}:{prefs:Preferences;setPrefs:(p:Preferences)=>void;close:()=>void}){const patch=(x:Partial<Preferences>)=>setPrefs({...prefs,...x});return <div className="settings-back"><aside className="settings-panel"><header><div><small>SYSTEM CONFIGURATION / 05</small><h2>基础设置</h2></div><button onClick={close}>×</button></header><section><div className="settings-title"><b>GLOBAL</b><span>全局设置</span></div><Toggle label="界面音效" code="SYSTEM AUDIO" value={prefs.sound} change={v=>patch({sound:v})}/><Toggle label="每次显示启动动画" code="BOOT SEQUENCE" value={prefs.boot} change={v=>patch({boot:v})}/><Toggle label="显示系统状态" code="TELEMETRY" value={prefs.showSystem} change={v=>patch({showSystem:v})}/></section><section><div className="settings-title"><b>MEMORY</b><span>灵感模块</span></div><Range label="同屏忆泡上限" value={prefs.density} min={6} max={30} step={1} change={v=>patch({density:v})}/><Range label="漂浮速度" value={prefs.motionSpeed} min={.4} max={1.8} step={.1} change={v=>patch({motionSpeed:v})}/><Toggle label="启用记忆衰减" code="MEMORY AGING" value={prefs.aging} change={v=>patch({aging:v})}/></section><div className="settings-foot"><span>CONFIGURATION SAVED LOCALLY</span><button onClick={()=>setPrefs(defaults)}>RESTORE DEFAULT</button></div></aside></div>}
function Toggle({label,code,value,change}:{label:string;code:string;value:boolean;change:(v:boolean)=>void}){return <div className="setting-row"><div><b>{label}</b><small>{code}</small></div><button className={`toggle ${value?"on":""}`} onClick={()=>change(!value)}><i/><span>{value?"ON":"OFF"}</span></button></div>}
function Range({label,value,min,max,step,change}:{label:string;value:number;min:number;max:number;step:number;change:(v:number)=>void}){return <div className="setting-row range-row"><div><b>{label}</b><small>VALUE / {value}</small></div><input type="range" min={min} max={max} step={step} value={value} onChange={e=>change(Number(e.target.value))}/></div>}
function AddDialog({close,add}:{close:()=>void;add:(a:string,b:string)=>void}){const[t,setT]=useState(""),[s,setS]=useState("");return <div className="modal-back"><div className="add-modal"><small>NEW MEMORY / 快速捕获</small><h2>记录一个新灵感</h2><label>NAME / 名称<input autoFocus value={t} onChange={e=>setT(e.target.value)} /></label><label>SOURCE / 来源链接<input value={s} onChange={e=>setS(e.target.value)}/></label><div><button onClick={close}>CANCEL</button><button className="primary" onClick={()=>add(t,s)}>SAVE MEMORY</button></div></div></div>}
